sudo: required
services:
  - docker

before_install:
  - docker build -t elgallopabman/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true elgallopabman/complex npm test

after_success:
  - docker build -t gallopabman/multi-client ./client
  - docker build -t gallopabman/multi-nginx ./nginx
  - docker build -t gallopabman/multi-server ./server
  - docker build -t gallopabman/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push elgallopabman/multi-client
  - docker push elgallopabman/multi-nginx
  - docker push elgallopabman/multi-server
  - docker push elgallopabman/multi-worker